'use client';

import { useState, type FormEvent } from 'react';
import { Button } from '@/components/common/Button';
import { Input } from '@/components/common/Input';
import { Select } from '@/components/common/Select';
import { FormActions } from '@/components/forms/FormActions';
import { FormError } from '@/components/forms/FormError';
import { FormField } from '@/components/forms/FormField';
import { CategoryImageField } from './CategoryImageField';
import { CATEGORY_CONSTRAINTS, CATEGORY_STATUS } from '@/constants';
import type { Category, CategoryStatus, CreateCategoryPayload, UpdateCategoryPayload } from '@/services/api';
import { ApiError } from '@/types/api';

type FieldErrors = {
  name?: string;
  description?: string;
};

interface CategoryFormProps {
  mode: 'create' | 'edit';
  initialCategory?: Category;
  isSubmitting: boolean;
  error: string | null;
  onCancel: () => void;
  onCreate?: (payload: CreateCategoryPayload) => Promise<void>;
  onUpdate?: (payload: UpdateCategoryPayload) => Promise<void>;
}

function validate(name: string, description: string): FieldErrors {
  const errors: FieldErrors = {};

  if (!name) {
    errors.name = 'Category name is required';
  } else if (name.length > CATEGORY_CONSTRAINTS.NAME_MAX) {
    errors.name = `Category name cannot exceed ${CATEGORY_CONSTRAINTS.NAME_MAX} characters`;
  } else if (!/[a-z0-9]/i.test(name)) {
    errors.name = 'Category name must contain letters or numbers';
  }

  if (description.length > CATEGORY_CONSTRAINTS.DESCRIPTION_MAX) {
    errors.description = `Category description cannot exceed ${CATEGORY_CONSTRAINTS.DESCRIPTION_MAX} characters`;
  }

  return errors;
}

export function CategoryForm({
  mode,
  initialCategory,
  isSubmitting,
  error,
  onCancel,
  onCreate,
  onUpdate,
}: CategoryFormProps) {
  const [name, setName] = useState(initialCategory?.name ?? '');
  const [description, setDescription] = useState(initialCategory?.description ?? '');
  const [status, setStatus] = useState<CategoryStatus>(initialCategory?.status ?? CATEGORY_STATUS.ACTIVE);
  const [imageKey, setImageKey] = useState<string | null | undefined>(undefined);
  const [isImageUploading, setIsImageUploading] = useState(false);
  const [fieldErrors, setFieldErrors] = useState<FieldErrors>({});
  const [formError, setFormError] = useState<string | null>(null);

  const isBusy = isSubmitting || isImageUploading;

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setFormError(null);

    const trimmedName = name.trim();
    const trimmedDescription = description.trim();
    const nextFieldErrors = validate(trimmedName, trimmedDescription);
    setFieldErrors(nextFieldErrors);

    if (Object.keys(nextFieldErrors).length > 0) {
      return;
    }

    if (isImageUploading) {
      setFormError('Wait for the image upload to finish before saving.');
      return;
    }

    try {
      if (mode === 'create') {
        const payload: CreateCategoryPayload = {
          name: trimmedName,
          status,
        };

        if (trimmedDescription) {
          payload.description = trimmedDescription;
        }

        if (imageKey) {
          payload.imageKey = imageKey;
        }

        await onCreate?.(payload);
        return;
      }

      const payload: UpdateCategoryPayload = {
        name: trimmedName,
        description: trimmedDescription ? trimmedDescription : null,
        status,
      };

      if (imageKey !== undefined) {
        payload.imageKey = imageKey;
      }

      await onUpdate?.(payload);
    } catch (err) {
      if (err instanceof ApiError && err.statusCode === 409) {
        setFieldErrors({ name: err.message });
      }
    }
  };

  return (
    <form onSubmit={handleSubmit} className="flex max-w-xl flex-col gap-4">
      <Input
        label="Name"
        value={name}
        onChange={(event) => {
          setName(event.target.value);
          setFieldErrors((current) => ({ ...current, name: undefined }));
        }}
        maxLength={CATEGORY_CONSTRAINTS.NAME_MAX}
        required
        disabled={isBusy}
        error={fieldErrors.name}
      />

      {mode === 'edit' && initialCategory && (
        <FormField label="Slug" hint="Generated by the Backend from the category name.">
          <p className="rounded-md border border-border bg-surface-muted px-3 py-2 font-mono text-sm text-text-secondary">
            {initialCategory.slug}
          </p>
        </FormField>
      )}

      <FormField label="Description" htmlFor="category-description" error={fieldErrors.description}>
        <textarea
          id="category-description"
          value={description}
          onChange={(event) => setDescription(event.target.value)}
          maxLength={CATEGORY_CONSTRAINTS.DESCRIPTION_MAX}
          disabled={isBusy}
          rows={4}
          className="w-full rounded-md border border-border bg-surface px-3 py-2 text-sm text-text placeholder:text-text-muted transition-colors focus-visible:border-primary focus-visible:outline-none disabled:cursor-not-allowed disabled:bg-surface-muted disabled:opacity-60"
        />
      </FormField>

      <Select
        label="Status"
        value={status}
        onChange={(event) => setStatus(event.target.value as CategoryStatus)}
        disabled={isBusy}
        options={[
          { value: CATEGORY_STATUS.ACTIVE, label: 'Active' },
          { value: CATEGORY_STATUS.INACTIVE, label: 'Inactive' },
        ]}
      />

      <CategoryImageField
        existingImageUrl={initialCategory?.imageUrl}
        disabled={isSubmitting}
        onChange={({ imageKey: nextKey, isUploading }) => {
          setImageKey(nextKey);
          setIsImageUploading(isUploading);
        }}
      />

      <FormError message={formError || (fieldErrors.name ? null : error)} />

      <FormActions>
        <Button type="button" variant="outline" onClick={onCancel} disabled={isBusy}>
          Cancel
        </Button>
        <Button type="submit" isLoading={isSubmitting} disabled={isBusy}>
          {mode === 'create' ? 'Save category' : 'Save changes'}
        </Button>
      </FormActions>
    </form>
  );
}
