import { apiClient } from './apiClient';
import type { ApiResponse } from '@/types/api';

/**
 * Backend Attribute admin contract:
 * GET    /api/v1/admin/attributes
 * POST   /api/v1/admin/attributes
 * GET    /api/v1/admin/attributes/:id
 * PATCH  /api/v1/admin/attributes/:id
 * DELETE /api/v1/admin/attributes/:id
 * GET    /api/v1/admin/attributes/:id/values
 * POST   /api/v1/admin/attributes/:id/values
 * PATCH  /api/v1/admin/attributes/:id/values/:valueId
 * DELETE /api/v1/admin/attributes/:id/values/:valueId
 *
 * `valueCount` is derived from the Attribute → AttributeValue relation.
 * `colorCode` is optional hex metadata on AttributeValue (`#RRGGBB`).
 * Slugs are generated by the Backend from name/value.
 */
export type Attribute = {
  id: string;
  name: string;
  slug: string;
  valueCount: number;
  createdAt: string;
  updatedAt: string;
};

export type AttributeValue = {
  id: string;
  attributeId: string;
  value: string;
  slug: string;
  colorCode: string | null;
  createdAt: string;
  updatedAt: string;
};

export type ListAttributesParams = {
  page?: number;
  limit?: number;
  search?: string;
};

export type ListAttributeValuesParams = {
  page?: number;
  limit?: number;
  search?: string;
};

export type CreateAttributePayload = {
  name: string;
};

export type UpdateAttributePayload = {
  name: string;
};

export type CreateAttributeValuePayload = {
  value: string;
  colorCode?: string;
};

export type UpdateAttributeValuePayload = {
  value?: string;
  colorCode?: string | null;
};

export type AttributeListResponse = ApiResponse<Attribute[]>;
export type AttributeResponse = ApiResponse<Attribute>;
export type AttributeValueListResponse = ApiResponse<AttributeValue[]>;
export type AttributeValueResponse = ApiResponse<AttributeValue>;

export function attributeSupportsColor(
  attribute: Pick<Attribute, 'slug'>,
  values: Pick<AttributeValue, 'colorCode'>[] = []
): boolean {
  if (values.some((item) => Boolean(item.colorCode))) {
    return true;
  }

  return attribute.slug === 'color';
}

export const attributeService = {
  list: (params: ListAttributesParams = {}) =>
    apiClient.get<AttributeListResponse>('/admin/attributes', { params }),

  getById: (id: string) => apiClient.get<AttributeResponse>(`/admin/attributes/${id}`),

  create: (payload: CreateAttributePayload) =>
    apiClient.post<AttributeResponse>('/admin/attributes', payload),

  update: (id: string, payload: UpdateAttributePayload) =>
    apiClient.patch<AttributeResponse>(`/admin/attributes/${id}`, payload),

  delete: (id: string) => apiClient.delete<ApiResponse>(`/admin/attributes/${id}`),

  listValues: (attributeId: string, params: ListAttributeValuesParams = {}) =>
    apiClient.get<AttributeValueListResponse>(`/admin/attributes/${attributeId}/values`, { params }),

  createValue: (attributeId: string, payload: CreateAttributeValuePayload) =>
    apiClient.post<AttributeValueResponse>(`/admin/attributes/${attributeId}/values`, payload),

  updateValue: (attributeId: string, valueId: string, payload: UpdateAttributeValuePayload) =>
    apiClient.patch<AttributeValueResponse>(
      `/admin/attributes/${attributeId}/values/${valueId}`,
      payload
    ),

  deleteValue: (attributeId: string, valueId: string) =>
    apiClient.delete<ApiResponse>(`/admin/attributes/${attributeId}/values/${valueId}`),
};
