'use client';

import { useState, type FormEvent } from 'react';
import { Button } from '@/components/common/Button';
import { Input } from '@/components/common/Input';
import { FormActions } from '@/components/forms/FormActions';
import { FormError } from '@/components/forms/FormError';
import { FormField } from '@/components/forms/FormField';
import { ATTRIBUTE_CONSTRAINTS } from '@/constants';
import type { Attribute, CreateAttributePayload, UpdateAttributePayload } from '@/services/api';
import { ApiError } from '@/types/api';

type FieldErrors = {
  name?: string;
};

interface AttributeFormProps {
  mode: 'create' | 'edit';
  initialAttribute?: Attribute;
  isSubmitting: boolean;
  error: string | null;
  onCancel: () => void;
  onCreate?: (payload: CreateAttributePayload) => Promise<void>;
  onUpdate?: (payload: UpdateAttributePayload) => Promise<void>;
}

function validate(name: string): FieldErrors {
  const errors: FieldErrors = {};

  if (!name) {
    errors.name = 'Attribute name is required';
  } else if (name.length > ATTRIBUTE_CONSTRAINTS.NAME_MAX) {
    errors.name = `Attribute name cannot exceed ${ATTRIBUTE_CONSTRAINTS.NAME_MAX} characters`;
  } else if (!/[a-z0-9]/i.test(name)) {
    errors.name = 'Attribute name must contain letters or numbers';
  }

  return errors;
}

export function AttributeForm({
  mode,
  initialAttribute,
  isSubmitting,
  error,
  onCancel,
  onCreate,
  onUpdate,
}: AttributeFormProps) {
  const [name, setName] = useState(initialAttribute?.name ?? '');
  const [fieldErrors, setFieldErrors] = useState<FieldErrors>({});
  const [formError, setFormError] = useState<string | null>(null);

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setFormError(null);

    const trimmedName = name.trim();
    const nextFieldErrors = validate(trimmedName);
    setFieldErrors(nextFieldErrors);

    if (Object.keys(nextFieldErrors).length > 0) {
      return;
    }

    try {
      if (mode === 'create') {
        await onCreate?.({ name: trimmedName });
        return;
      }

      await onUpdate?.({ name: trimmedName });
    } catch (err) {
      if (err instanceof ApiError && err.statusCode === 409) {
        setFieldErrors({ name: err.message });
      }
    }
  };

  return (
    <form onSubmit={handleSubmit} className="flex max-w-xl flex-col gap-4">
      <Input
        label="Attribute name"
        value={name}
        onChange={(event) => {
          setName(event.target.value);
          setFieldErrors((current) => ({ ...current, name: undefined }));
        }}
        maxLength={ATTRIBUTE_CONSTRAINTS.NAME_MAX}
        required
        disabled={isSubmitting}
        error={fieldErrors.name}
      />

      {mode === 'edit' && initialAttribute && (
        <FormField label="Slug" hint="Generated by the Backend from the attribute name.">
          <p className="rounded-md border border-border bg-surface-muted px-3 py-2 font-mono text-sm text-text-secondary">
            {initialAttribute.slug}
          </p>
        </FormField>
      )}

      <FormError message={formError || (fieldErrors.name ? null : error)} />

      <FormActions>
        <Button type="button" variant="outline" onClick={onCancel} disabled={isSubmitting}>
          Cancel
        </Button>
        <Button type="submit" isLoading={isSubmitting} disabled={isSubmitting}>
          {mode === 'create' ? 'Create' : 'Save changes'}
        </Button>
      </FormActions>
    </form>
  );
}
